#!/bin/ash
# Now using the util-linux losetup (losetup-FULL),

LOSETUP_BIN=/sbin/losetup

[ -L $LOSETUP_BIN ] && LOSETUP_BIN=$(readlink $LOSETUP_BIN)

if [ "$(file $LOSETUP_BIN | grep "ELF" | grep "LSB")" != "" ] && [ "$(basename $LOSETUP_BIN)" != "busybox" ]; then
	
	# make losetup's output look more like busybox losetup..
	# - Older losetup versions require the -a param
	# - Recent losetup versions don't require the -a param
	#   but the output is bit different if -a is not specified
	
 	if [ "$1" = "" ] ; then
		RETSTUFF="`$LOSETUP_BIN -a`"
		RETVAL=$?
	else
		RETSTUFF="`$LOSETUP_BIN "$@"`"
		RETVAL=$?
	fi
	
	echo "$RETSTUFF" | sed -e 's% (/% /%' -e 's%)$%%'

else
	
	LOSETUP_BIN=/sbin/losetup-FULL
	
	[ -L $LOSETUP_BIN ] && LOSETUP_BIN=$(readlink $LOSETUP_BIN)

	if [ "$(file $LOSETUP_BIN | grep "ELF" | grep "LSB")" != "" ] && [ "$(basename $LOSETUP_BIN)" != "busybox" ]; then
	
	 	if [ "$1" = "" ] ; then
			RETSTUFF="`$LOSETUP_BIN -a`"
			RETVAL=$?
		else
			RETSTUFF="`$LOSETUP_BIN "$@"`"
			RETVAL=$?
		fi
		
		echo "$RETSTUFF" | sed -e 's% (/% /%' -e 's%)$%%'
	
	else
	 	RETSTUFF="`busybox losetup "$@"`"
		RETVAL=$?
		echo "$RETSTUFF"
	fi
	
fi

exit $RETVAL

### END ###

#---------------
# losetup 2.20.1 (tahrpup)
#---------------
## losetup -a
#/dev/loop0: [0801]:194315 (/mnt/dev_save/PUPPYBOOT/precise/puppy_precise_5.7.1.sfs)
#/dev/loop1: [0801]:194314 (/mnt/dev_save/PUPPYBOOT/precise/fdrv_precise_5.7.1.sfs)
#/dev/loop2: [0801]:194311 (/mnt/dev_save/PUPPYBOOT/precise/zdrv_precise_5.7.1.sfs)
#/dev/loop3: [0801]:194320 (/mnt/dev_save/PUPPYBOOT/precise/ydrv_precise_5.7.1.sfs)
#/dev/loop4: [0801]:194306 (/mnt/dev_save/PUPPYBOOT/precise/adrv_precise_5.7.1.sfs)
#/dev/loop5: [0801]:194308 (/mnt/dev_save/PUPPYBOOT/precise/precisesave.4fs)
#/dev/loop6: [0801]:194307 (/initrd/mnt/dev_save/PUPPYBOOT/precise/devx_precise_5.7.1.sfs)

#-------------
# busybox 1.25
#-------------
## busybox losetup -a
#/dev/loop0: 0 /mnt/dev_save/PUPPYBOOT/precise/puppy_precise_5.7.1.sfs
#/dev/loop1: 0 /mnt/dev_save/PUPPYBOOT/precise/fdrv_precise_5.7.1.sfs
#/dev/loop2: 0 /mnt/dev_save/PUPPYBOOT/precise/zdrv_precise_5.7.1.sfs
#/dev/loop3: 0 /mnt/dev_save/PUPPYBOOT/precise/ydrv_precise_5.7.1.sfs
#/dev/loop4: 0 /mnt/dev_save/PUPPYBOOT/precise/adrv_precise_5.7.1.sfs
#/dev/loop5: 0 /mnt/dev_save/PUPPYBOOT/precise/precisesave.4fs
#/dev/loop6: 0 /initrd/mnt/dev_save/PUPPYBOOT/precise/devx_precise_5.7.1.sfs

