#!/bin/bash
#update local dep file from remote dep file

# Define variables
DEPS_DIR="/var/packages/repos/slack-deps/dep-files"
URL="https://slackware.uk/slackel/x86_64/slackware-current/deps/"
LOCAL_METADATA="$(dirname $DEPS_DIR)/last_metadata.txt"
REMOTE_METADATA="$(dirname $DEPS_DIR)/remote_metadata.txt"

[ -f /etc/slackdep-fetcher.cfg ] && . /etc/slackdep-fetcher.cfg

# Create deps directory if it does not exist
if [ ! -d "$DEPS_DIR" ]; then
    echo "Creating $DEPS_DIR..."
    mkdir -p "$DEPS_DIR"
fi

cd $(dirname $DEPS_DIR)

# Check if the remote server is reachable
echo "Checking $URL"
if ! wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.61 Safari/537.36" --dns-timeout=3 --connect-timeout=3 --spider "$URL" &>/dev/null; then
    echo "Error: Unable to reach $URL. Exiting."
    exit 1
fi


# Fetch and convert webpage to metadata format: Name|Last Modified
echo "Fetching $URL"
wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.61 Safari/537.36" --dns-timeout=3 --connect-timeout=3 --read-timeout=30 -q -O- "$URL" | grep -oE '<a href="[^"]+\.dep".*?>.*?</a>.*?[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}' | sed -E 's/<a href="([^"]+\.dep)".*?>(.*?)<\/a>.*?([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2})/\1|\3/' > "$REMOTE_METADATA"

if [ $? -eq 0 ]; then

	# Compare with local metadata using md5sum
	if [ -f "$LOCAL_METADATA" ] && [ "$(md5sum "$LOCAL_METADATA" | awk '{print $1}')" == "$(md5sum "$REMOTE_METADATA" | awk '{print $1}')" ]; then
		echo "No changes detected in deps folder. Exiting."
		rm "$REMOTE_METADATA"
		exit 0
	fi

	echo "Processing metadata..."
	# Scan for new or modified files
	while IFS='|' read -r file remote_modified; do
		LOCAL_FILE="$DEPS_DIR/$file"
		
		if [ ! -f "$LOCAL_FILE" ]; then
		  msg="Downloading"
		  GO_WGET=1
		elif ! grep -q "$file|$remote_modified" "$LOCAL_METADATA" 2>/dev/null; then
		  
		  if [ "$(grep -q "$file|" "$LOCAL_METADATA")" != "" ]; then
			msg="Updating"
		  else
			msg="Downloading"
		  fi
		  
		  GO_WGET=1
		else
		  GO_WGET=0
		fi
		
		if [ $GO_WGET -ne 0 ]; then
			echo "$msg: $file..."
			wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.61 Safari/537.36" --timeout=3 -q -O "$LOCAL_FILE" "$URL$file"
		fi

	done < "$REMOTE_METADATA"

	# Update local metadata
	echo "Updating local metadata..."
	mv -f "$REMOTE_METADATA" "$LOCAL_METADATA"

	echo "Fetching complete"

fi
