name: Build Puppy Full Live CD

on:
  #schedule:
    #- cron: '0 2 */20 * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:sid
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Step 1: Trigger Kernel Workflow & Download Artifacts ---
      - name: Trigger Kernel Workflow & Wait
        uses: aurelien-bree/action-workflow-dispatch@v1.2.0
        with:
          workflow: linux-kernel-aufs.yml
          repo: rizalmart/puppy-linux-kernel-maker
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true

      - name: Download Kernel Artifacts
        uses: actions/download-artifact@v4
        with:
          repository: rizalmart/puppy-linux-kernel-maker
          path: puppy-downloaded/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # --- Step 2: Trigger Firmware/Driver Workflow & Download Artifacts ---
      - name: Trigger Firmware Driver Workflow & Wait
        uses: aurelien-bree/action-workflow-dispatch@v1.2.0
        with:
          workflow: firmware-driver.yml
          repo: rizalmart/puppy-linux-kernel-maker
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true

      - name: Download Firmware Driver Artifacts
        uses: actions/download-artifact@v4
        with:
          repository: rizalmart/puppy-linux-kernel-maker
          path: puppy-downloaded/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # --- Flatten Subdirectories ---
      - name: Flatten Artifact Directory Structure
        shell: bash
        run: |
          # Move files sitting inside artifact subfolders up into puppy-livecd-build
          find puppy-downloaded/ -mindepth 2 -type f -exec mv -t puppy-downloaded/ {} +

      # --- Main Build Process ---
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y \
            busybox \
            squashfs-tools wget xz-utils ca-certificates desktop-file-utils openssl \
            wget kmod curl cpio coreutils python3 python3-pip unzip binutils patch genisoimage

      - name: Building compiling puppy core applications
        shell: bash
        run: |
              . ./build-settings.cfg
              cp -rf ./puppy-source-builds /
              chmod +x ./external-tools/compile-puppy-core-apps.sh
              ./external-tools/compile-puppy-core-apps.sh
              mkdir -p puppy-core-apps-build
              cp -rf /usr/local/* ./puppy-core-apps-build/

      - name: Building debian puppy filesystem
        shell: bash
        run: |
         
              . ./DISTRO_SPECS

              echo "DISTRO_NAME=$DISTRO_NAME" >>  $GITHUB_ENV
              echo "DISTRO_VERSION=$DISTRO_VERSION" >>  $GITHUB_ENV
              echo "DISTRO_PUPPYSFS=$DISTRO_PUPPYSFS" >>  $GITHUB_ENV

              export TERM=xterm
              
              chmod +x ./01-build-debian-puppy.sh
              ./01-build-debian-puppy.sh

              . ./build-settings.cfg
              cp -rf ./puppy-core-apps-build/* $ROOTFS/usr/local/
              chroot $ROOTFS /usr/lib/puppy/sbin/update-cache.sh y

      - name: Prepare Live CD
        shell: bash
        run: |              
              chmod +x ./02-prepare-livecd.sh
              ./02-prepare-livecd.sh
              
      - name: Packing puppy filesystem into main sfs file
        shell: bash
        run: |      
              chmod +x ./03-pack-sfs.sh
              ./03-pack-sfs.sh

      - name: Process initrd
        shell: bash
        run: |              
              chmod +x ./04-process-initrd.sh
              ./04-process-initrd.sh

      - name: Build Live CD
        shell: bash
        run: |

              . ./DISTRO_SPECS

              find ./puppy-downloaded -type f -name "*.zip" | xargs -i unzip {} -d ./puppy-livecd-build/

              cp -f ./puppy-downloaded/huge-kernel-*-aufs.sfs ./puppy-livecd-build/$DISTRO_ZDRVSFS
              cp -f ./puppy-downloaded/linux-firmware-pconly.sfs ./puppy-livecd-build/$DISTRO_FDRVSFS
        
              chmod +x ./05-build-livecd.sh
              ./05-build-livecd.sh
                         
      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_NAME }}-${{ env.DISTRO_VERSION }}-main-files
          path: |
                puppy-livecd-build/${{ env.DISTRO_PUPPYSFS }}
                puppy-livecd-build/initrd.xz
          compression-level: 0 

      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_NAME }}-${{ env.DISTRO_VERSION }}-initrd
          path: puppy-livecd-build/initrd.xz
          compression-level: 0 

      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_PUPPYSFS }}
          path: puppy-livecd-build/${{ env.DISTRO_PUPPYSFS }}
          compression-level: 0
